name: qg

on:
  pull_request:

jobs:
  qg:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout source code
        uses: actions/checkout@v3
      - name: ğŸ§‘ğŸ¼â€ğŸ’» Approval by Tech Lead
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: bernhardrode
          minimum-approvals: 1
          issue-title: "Tech Lead Approval"
