name: ğŸ‘¨ğŸ½â€ğŸ’¼ Prepare a QG4

on:
  pull_request:
    branches: [main]

jobs:
  qg:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§‘ğŸ¼â€ğŸ’» Get approval by Tech Lead
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: BernhardRode
          minimum-approvals: 1
          issue-title: "Tech Lead Approval"
