name: QG

on:
  pull_request:
    branches: [master]

jobs:
  qg:
    name: ğŸ‘¨ğŸ½â€ğŸ’¼ Prepare a QG4
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout source code
        uses: actions/checkout@v3
      - name: ğŸ§‘ğŸ¼â€ğŸ’» Get approval by Tech Lead
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: bernhardrode
          minimum-approvals: 1
          issue-title: "Tech Lead Approval"
