name: ğŸª© Run semantic release

on:
  push:
    branches:
      - main
      - next
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: ğŸ›’ Checkout source code
        uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: ğŸ§‘ğŸ¼â€ğŸ’» Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          scope: "@bosch-engineering-test"

      - name: ğŸ§± Install dependencies
        run: |
          npm i
          npm ci --ws

      - name: ğŸš§ Build packages
        run: |
          npm run build --ws --if-present

      - name: ğŸš› Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx auto shipit
